# fly.toml app configuration file generated for fastapi-book-project-infinitech on 2025-02-14T17:02:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-book-project-infinitech'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

