name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix Docker Dependencies
        run: |
          sudo apt-get remove -y containerd.io containerd docker.io docker-ce docker-ce-cli
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Start Docker Service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      - name: Deploy using Docker Compose
        run: |
          sudo docker compose down
          sudo docker compose up -d --build
