name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Add EC2 to known hosts
        run: ssh-keyscan 54.160.243.61 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem ec2-user@54.160.243.61 << 'EOF'
            cd /home/ec2-user/your-project-folder  # Change this to your actual project path
            git pull origin main
            sudo systemctl restart your-service-name  # Restart FastAPI app if needed
          EOF
