name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Moby (Docker Alternative)
        run: |
          sudo apt-get update
          sudo apt-get install -y moby-engine moby-cli

      - name: Start Docker Service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Check Docker Version
        run: |
          docker --version
          docker compose version || docker-compose version

      - name: Deploy using Docker Compose
        run: |
          COMPOSE_CMD=$(command -v docker-compose || echo "docker compose")
          sudo $COMPOSE_CMD down
          sudo $COMPOSE_CMD up -d --build
